version: '2'
volumes:
  kata_jenkins_data:
    external: true
  kata_sonarqube_conf:
    external: true
  kata_sonarqube_data:
    external: true
  kata_sonarqube_extensions:
    external: true
  kata_nexus_data:
    external: true

services:
  kata-jenkins:
    container_name: kata-jenkins
    build:
      context: ./
      dockerfile: Dockerfile-kata-jenkins
    ports:
      - "8081:8080"
      - "50001:50000"
    volumes:
      - kata_jenkins_data:/var/jenkins_home

  kata-sonar:
    container_name: kata-sonar
    image: "sonarqube:8.4.1-community"
    ports:
      - "9002:9000"
    volumes:
      - kata_sonarqube_conf:/opt/sonarqube/conf
      - kata_sonarqube_data:/opt/sonarqube/data
      - kata_sonarqube_extensions:/opt/sonarqube/extensions

  kata-nexus:
    container_name: kata-nexus
    image: "sonatype/nexus:oss"
    ports:
      - "8083:8081"
    volumes:
      - kata_nexus_data:/sonatype/oss

